# Generated by Django 4.2.4 on 2023-10-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profiles',
            field=models.ManyToManyField(blank=True, null=True, to='app.profile'),
        ),
    ]
