# Generated by Django 4.2.4 on 2023-10-18 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_post_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profiles',
        ),
        migrations.AddField(
            model_name='post',
            name='profiles',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
