# Generated by Django 4.2.4 on 2023-10-18 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_post_profiles_post_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profiles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
